return {
  -- "olimorris/codecompanion.nvim",
  -- version="17.*",
  -- opts = {
    -- strategies = {
      -- chat = {
        -- name = "copilot",
        -- model = "claude-sonnet-4"
      -- },
      -- inline = {
        -- name = "copilot",
        -- model = "claude-sonnet-4"
      -- },
    -- },
  -- },
  -- dependencies = {
    -- "nvim-lua/plenary.nvim",
  -- },
  -- extensions = {
    -- mcphub = {
      -- callback = "mcphub.extensions.codecompanion",
      -- opts = {
        -- make_vars = true,
        -- make_slash_commands = true,
        -- show_result_in_chat = true
      -- }
    -- }
  -- }
}
